server:
  port: 8080
  servlet:
    application-display-name: scma

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/scmadb
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

admin:
  firstName: admin
  lastName: admin
  email: admin@admin.com
  username: admin
  password: admin